version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GEMINI_API_KEY=${GEMINI_API_KEY}
    container_name: django_container
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DJANGO_SETTINGS_MODULE=career_development.settings
      - DJANGO_DEBUG=False
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "80:8000"
      - "8001:8001"
    volumes:
      - ./media:/app/media
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
