version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GEMINI_API_KEY=${GEMINI_API_KEY}
    container_name: django_container
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DJANGO_SETTINGS_MODULE=career_development.settings
      - DJANGO_DEBUG=False
      - REDIS_URL=redis://redis:6379/0
    expose:
      - "8000"
      - "8001"
    volumes:
      - ./media:/app/media
      - ./career_development/staticfiles:/app/staticfiles
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/app/media
      - ./career_development/staticfiles:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
