version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    container_name: django_container
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DJANGO_SETTINGS_MODULE: career_development.settings
      DJANGO_DEBUG: 'False'
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./media:/app/media
      - ./core/static:/app/static
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:1.21.6
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./core/static:/app/static
      - ./media:/app/media
      - /etc/letsencrypt/live/virtualventure.shariqshaukat.online:/etc/letsencrypt/live/virtualventure.shariqshaukat.online
      - /etc/letsencrypt/archive/virtualventure.shariqshaukat.online:/etc/letsencrypt/archive/virtualventure.shariqshaukat.online
    depends_on:
      - web

volumes:
  redis_data:
  static:
  media:
