# Generated by Django 5.0.6 on 2024-07-08 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import json

def set_default_json_fields(apps, schema_editor):
    Profile = apps.get_model('core', 'Profile')
    for profile in Profile.objects.all():
        if profile.skill_assessment is None:
            profile.skill_assessment = json.dumps({})
        if profile.career_progress is None:
            profile.career_progress = json.dumps({})
        if profile.resume_advice is None:
            profile.resume_advice = ""
        if profile.matched_jobs is None:
            profile.matched_jobs = json.dumps({})
        if profile.learning_resources is None:
            profile.learning_resources = json.dumps({})
        if profile.networking_opportunities is None:
            profile.networking_opportunities = json.dumps({})
        if profile.career_recommendations is None:
            profile.career_recommendations = json.dumps({})
        if profile.job_prospects is None:
            profile.job_prospects = json.dumps({})
        profile.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('career_interests', models.CharField(blank=True, max_length=255)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('career_goals', models.TextField(blank=True)),
                ('professional_experience', models.TextField(blank=True)),
                ('resume_job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('resume_skills_experiences', models.TextField(blank=True)),
                ('resume_education', models.TextField(blank=True)),
                ('skill_assessment', models.JSONField(blank=True, default=dict, null=True)),
                ('resume_advice', models.TextField(blank=True, default='')),
                ('matched_jobs', models.JSONField(blank=True, default=dict, null=True)),
                ('learning_resources', models.JSONField(blank=True, default=dict, null=True)),
                ('networking_opportunities', models.JSONField(blank=True, default=dict, null=True)),
                ('career_recommendations', models.JSONField(blank=True, default=dict, null=True)),
                ('job_prospects', models.JSONField(blank=True, default=dict, null=True)),
                ('career_progress', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(set_default_json_fields),
    ]
