# Generated by Django 5.0.6 on 2024-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_resume_advice_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume_advice_format',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume_advice_job_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume_advice_skills_qualifications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resume_advice_text',
        ),
        migrations.AddField(
            model_name='profile',
            name='css_skill_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='django_skill_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='html_skill_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='js_skill_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='python_skill_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
