# Generated by Django 5.0.6 on 2024-07-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_resume_advice_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certifications_awards',
            field=models.TextField(blank=True),
        ),
    ]
