# Generated by Django 5.0.6 on 2024-07-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_career_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='finance_skill_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='management_skill_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='marketing_skill_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sales_skill_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='career_interests',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='career_progress',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='career_recommendations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_prospects',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='learning_resources',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='matched_jobs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='networking_opportunities',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_advice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_assessment',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='css_skill_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='django_skill_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='html_skill_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='js_skill_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='python_skill_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
