# Generated by Django 5.0.6 on 2024-06-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_connection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='skills',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='professional_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
