# Generated by Django 5.0.6 on 2024-07-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_finance_skill_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='css_skill_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='django_skill_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='html_skill_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='js_skill_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='python_skill_level',
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_levels',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
