# Generated by Django 5.0.6 on 2024-06-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
