# Generated by Django 5.0.6 on 2024-07-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_profile_css_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='css_skill_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='django_skill_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='html_skill_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='js_skill_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='python_skill_level',
            field=models.IntegerField(default=1),
        ),
    ]
