# Generated by Django 5.0.6 on 2024-07-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_learning_resources_profile_matched_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_prospects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
