# Generated by Django 5.0.6 on 2024-07-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_career_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='drawing_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='finance_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='management_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='marketing_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='painting_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photography_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sales_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sculpting_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career_progress',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career_recommendations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='css_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='django_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='html_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_prospects',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='js_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='learning_resources',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matched_jobs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='networking_opportunities',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='python_skill_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill_assessment',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill_levels',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
