# Generated by Django 5.0.6 on 2024-07-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_pathway',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
