# Generated by Django 5.0.6 on 2024-07-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_career_pathway'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='learning_pathway',
            field=models.TextField(blank=True, default=''),
        ),
    ]
