# Generated by Django 5.0.6 on 2024-07-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notification_target_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
