# Generated by Django 5.0.6 on 2024-08-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_badge_userbadge_badge_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbadge',
            old_name='awarded_at',
            new_name='awarded_on',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='users',
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
